### ISSUE TITLE
package.json file format error in line 17 

### ISSUE THREAD

**Issue by VyaWave** [jmx164491960/load-on-demand#1]
```
"build": "cross-env NODE_ENV=production env_config=prod node build/build.js",
```

should be 
```
"build": "cross-env NODE_ENV=production env_config=prod node build/build.js"
```
Just one more comma

**Comment by adamma1024** [comment]
> ```
> "build": "cross-env NODE_ENV=production env_config=prod node build/build.js",
> ```
> 
> should be
> 
> ```
> "build": "cross-env NODE_ENV=production env_config=prod node build/build.js"
> ```
> 
> Just one more comma

It's so stupid problem, and wasted my one minute

**Comment by VyaWave** [comment]
What happen?!!!
